[package]
name = "legal_ruqyah_bot"
version = "0.1.0"
edition = "2021"
authors = ["Badr Azizi <badrazizi3@gmail.com>"]

[dependencies]
teloxide = { version = "0.13", features = ["macros"] }
tokio = { version = "1.41.0", features = ["rt-multi-thread", "macros"] }
serde = "1.0.214"
serde_json = "1.0.132"
strum = "0.26"
strum_macros = "0.26"
