on:
  release:
    types: [created]
  
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    name: release ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
          - target: x86_64-unknown-linux-musl
          - target: aarch64-unknown-linux-gnu
          - target: armv7-unknown-linux-gnueabihf
    steps:
      - name: Install packages
        run: |
          sudo apt-get install -y build-essential make pkg-config perl libudev-dev libssl-dev
          
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}